version: "3.7"
services:
  db:
    image: postgres:12-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  api:
    build: ./server
    ports:
      - 8081:8081
    restart: on-failure
    depends_on:
      - db
  app:
    stdin_open: true
    restart: always
    build: ./client
    ports:
      - 3001:3000
    volumes:
      - ./client:/app/
      - /app/node_modules/